// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: link/link.proto

package link

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing program to link, commarea and commarea length.
type CommReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkProg string `protobuf:"bytes,1,opt,name=link_prog,json=linkProg,proto3" json:"link_prog,omitempty"`
	CommLen  int32  `protobuf:"varint,2,opt,name=comm_len,json=commLen,proto3" json:"comm_len,omitempty"`
	InputMsg []byte `protobuf:"bytes,3,opt,name=input_msg,json=inputMsg,proto3" json:"input_msg,omitempty"`
}

func (x *CommReq) Reset() {
	*x = CommReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommReq) ProtoMessage() {}

func (x *CommReq) ProtoReflect() protoreflect.Message {
	mi := &file_link_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommReq.ProtoReflect.Descriptor instead.
func (*CommReq) Descriptor() ([]byte, []int) {
	return file_link_link_proto_rawDescGZIP(), []int{0}
}

func (x *CommReq) GetLinkProg() string {
	if x != nil {
		return x.LinkProg
	}
	return ""
}

func (x *CommReq) GetCommLen() int32 {
	if x != nil {
		return x.CommLen
	}
	return 0
}

func (x *CommReq) GetInputMsg() []byte {
	if x != nil {
		return x.InputMsg
	}
	return nil
}

// The response message containing commarea
type CommResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputMsg []byte `protobuf:"bytes,1,opt,name=output_msg,json=outputMsg,proto3" json:"output_msg,omitempty"`
}

func (x *CommResp) Reset() {
	*x = CommResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommResp) ProtoMessage() {}

func (x *CommResp) ProtoReflect() protoreflect.Message {
	mi := &file_link_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommResp.ProtoReflect.Descriptor instead.
func (*CommResp) Descriptor() ([]byte, []int) {
	return file_link_link_proto_rawDescGZIP(), []int{1}
}

func (x *CommResp) GetOutputMsg() []byte {
	if x != nil {
		return x.OutputMsg
	}
	return nil
}

var File_link_link_proto protoreflect.FileDescriptor

var file_link_link_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x5e, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x4c, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4d,
	0x73, 0x67, 0x32, 0x3a, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2b, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x41, 0x72, 0x65, 0x61, 0x12, 0x0d, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x38, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2f, 0x64, 0x38, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_link_link_proto_rawDescOnce sync.Once
	file_link_link_proto_rawDescData = file_link_link_proto_rawDesc
)

func file_link_link_proto_rawDescGZIP() []byte {
	file_link_link_proto_rawDescOnce.Do(func() {
		file_link_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_link_link_proto_rawDescData)
	})
	return file_link_link_proto_rawDescData
}

var file_link_link_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_link_link_proto_goTypes = []interface{}{
	(*CommReq)(nil),  // 0: link.CommReq
	(*CommResp)(nil), // 1: link.CommResp
}
var file_link_link_proto_depIdxs = []int32{
	0, // 0: link.LinkService.CommArea:input_type -> link.CommReq
	1, // 1: link.LinkService.CommArea:output_type -> link.CommResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_link_link_proto_init() }
func file_link_link_proto_init() {
	if File_link_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_link_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_link_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_link_proto_goTypes,
		DependencyIndexes: file_link_link_proto_depIdxs,
		MessageInfos:      file_link_link_proto_msgTypes,
	}.Build()
	File_link_link_proto = out.File
	file_link_link_proto_rawDesc = nil
	file_link_link_proto_goTypes = nil
	file_link_link_proto_depIdxs = nil
}
